---
version: '3'
services:
  db:
    image: postgres:latest
    volumes:
    - "db-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
  web:
    build: .
    command: bundle exec rails s -p 26906 -b 0.0.0.0
    volumes:
    - .:/app
    - bundle-cache:/usr/local/bundle
    ports:
    - "26906:26906"
    depends_on:
    - db
    environment:
      DATABASE_URL: postgres://postgres:mysecretpassword@db:5432
volumes:
  db-data:
  bundle-cache:
